export * from './Enums'
export {default as Person} from './PersonClass'
export {Person as PersonInterface} from './PersonInterface'
export { Employee } from './Employee'
export { Customer } from './Customer'